Create buildings scripts
MountainCat1/TileTowns pull request #76
Opened 2023-09-15 12:51 UTC by BartekBanas

2023-09-15 14:07 UTC, MountainCat1 requested changes
hit me up when you done so i can look it up, i kinda ignore push notifications from github xP

2023-09-15 14:07 UTC, MountainCat1 commented on TileTowns/Assets/Scripts/Buildings/Church.cs
first off, dont hard code amount of immigration that building gives per worker
second - 50 is way too much x)

2023-09-15 14:07 UTC, MountainCat1 commented on TileTowns/Assets/Scripts/Buildings/House.cs
again i see a hard code, pls use 
[SerializeField] private float something;

2023-09-15 14:07 UTC, MountainCat1 commented on TileTowns/Assets/Scripts/Buildings/Woodmill.cs
this one is cool but shoulding it get additional income per forest around it??

2023-09-15 14:07 UTC, MountainCat1 commented on TileTowns/Assets/Scripts/Buildings/Church.cs
also cost per worker? did we plan it?

2023-09-15 14:14 UTC, BartekBanas commented on TileTowns/Assets/Scripts/Buildings/Church.cs
MoneyPerWorker didn't look planned out to me either xD
And I thought it makes sense alike to Stronghold for example, but I guess it might be better without it.
It's all up to balance

2023-09-15 14:17 UTC, BartekBanas commented on TileTowns/Assets/Scripts/Buildings/Church.cs
You did that yourself for Farm xD
I was just trying to play along

2023-09-16 17:32 UTC, MountainCat1 approved these changes

2023-09-16 17:32 UTC, merged